### PR TITLE
Create LICENSE.md

### PR DESCRIPTION
**Pull request by shakibaRafiee**
This resolves issue #1

### CODE REVIEW

**Review by xofbd — APPROVED** [review]
Looks good to me!

**Comment by xofbd** [comment]
With GitHub, you can reference issues by typing "#", This is helpful as people like to say:
> This resolves issue #1 

Try it out yourself!

**Comment by i02132002** [comment]
Look good to me, too!

**Review by i02132002 — APPROVED** [review]
Looks good!

**Pull request merged**
